### ISSUE TITLE
0.6.0 Release Target

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hsds#47]
This issue is to document the set of features/bug fixes for the next (v0.6) HSDS release

- [X] Posix storage - #39
- [X] Azure blob storage - #40
- [X] Azure Active Directory authentication - #41
- [X] ~~Kerberos~~ OpenID Authentication - #52 (was #36) 
- [X] AKS (Azure Kubernetes) support - #42
- [X] DCOS support - #31
- [x] AWS Lambda for chunk reading - #43
- [X] Python packaging for HSDS - #26 
- [X] CORS handling with aiohttp-cors - #32
- [X] Move to Python 3.8 - #44
- [X] Remove passwords from build image - #45
- [x] RBAC (role based access control) support - #46
- [X] Domain checksums - #48
- [X] Config file - #50
- [X] Blosc support - #65
- [X] Enable HTTP Compression -  #66

**Comment by jjaraalm** [comment]
Can I suggest also a cleanup of the config settings? We could use a single yaml config file instead of environment variables to reduce clutter and make setup easier.

**Comment by jreadey** [comment]
@jjaraalm - since we are now mounting the admin/config directory for the password file, that makes sense to just pull config settings in the same way.

**Comment by jreadey** [comment]
Release is tagged and docker image pushed to Docker Hub.
