### ISSUE TITLE
0.7.0 Release Target

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hsds#82]
This issue is to document the set of features for the next (v0.7) HSDS release

- [X] Keycloak Authentication - #74
- [X] OpenShift support - #75
- [X] Tool for updating references to linked files - #78
- [X] Azure RBAC using AD Groups - #79
- [X] Enable AWS Lambda - #93 
- [x] Enable Direct Access model - #94
- [X] Fix for nodes stuck in waiting due to scaling event - #104
- [X] Fancy Indexing support - #109
- [X] No Docker option - #115 
- [X] Add HSDS to PyPI - #116
- [X] Streaming support - #126

Feel free to comment on this issue with additional features you'd like to see addressed.

**Comment by jreadey** [comment]
I've bumped the Azure Policy based feature for now and have added Lambda and Direct Access to the release target.

**Comment by bilalshaikh42** [comment]
Is #104 now included in this target? Seems like it was a simple change?

**Comment by jreadey** [comment]
Added #104 as well as #126.

**Comment by jreadey** [comment]
All features complete - closing issue!

**Comment by TManhente** [comment]
I've noticed that a [Docker image tagged `v0.7.0`](https://hub.docker.com/layers/hdfgroup/hsds/v0.7.0/images/sha256-c63bf730084b2c9b662c0d6d680d4b5a1e4c17b1554633f48e9204885c98c371) was published to Docker Hub a week ago, but there is no v0.7.0 release or Git tag when looking at the GitHub repository. Is the v0.7.0 finished and officially released?

**Comment by jreadey** [comment]
Yes it is finished (finally!) and officially released.  I've created the release and tag just now.
